apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: anki-vocabulary
  region: eu-central-1
nodeGroups:
  - name: spot-node-group-2vcpu-2gb
    desiredCapacity: 1
    instancesDistribution:
      instanceTypes: ["t3a.small"]